### ISSUE TITLE
v2.0.x Chore - add custom ast-grep rules

### ISSUE THREAD

**Issue by reactive-firewall** [reactive-firewall/multicast#207]
# project specific ast-grep rules

**the powerful tool `ast-grep` could be better leveraged for the project, with targeted custom rules**

### Context and background information

Regarding a recent review of 'docs/FAQ.md' @coderabbitai observed 

**API examples are correct but could be improved**

The Python API examples in the FAQ are accurate and match the implementation, as they use the correct class (`McastDispatch`) and method (`doStep`) with proper argument structure. However, the examples could be enhanced by:

- Adding error handling with try-except blocks (already present)
- Including comments about default values (port=59259, group='224.0.0.1')
- Mentioning that the message argument is required
- Documenting that the function returns a tuple of (success_bool, result)

The following scripts were executed for the analysis:

Script:

```shell
#! /bin/bash
# Description: Verify Python API examples match the implementation

# Test: Check if the API classes and methods exist
ast-grep --pattern $'class McastRECV {
  $$$
  doStep($$$) {
    $$$
  }
}'

ast-grep --pattern $'class McastHEAR {
  $$$
  doStep($$$) {
    $$$
  }
}'

```

Length of output: 153

---

Script:

```shell
#!/bin/bash
# Let's check for the actual McastDispatch class and its methods
ast-grep --pattern $'class McastDispatch {
  $$$
  doStep($$$) {
    $$$
  }
}'

# Search for any Python files that might contain the implementation
fd -e py --exec cat {}

# Look for specific imports and usage patterns
rg "class Mcast" -A 5

```

Length of output: 270032

---

Script:

```shell
#!/bin/bash
# Let's check for McastDispatch.doStep implementation
ast-grep --pattern $'class McastDispatch {
  $$$
  doStep($$$) {
    $$$
  }
}'

# Let's verify the example's SAY arguments match the implementation
rg "McastDispatch\(\)\.doStep\(\[\"SAY\"," -A 2

```

Length of output: 838

---

Script:

```shell
#!/bin/bash
# Let's check the actual implementation of McastSAY class
ast-grep --pattern $'class McastSAY {
  $$$
  doStep($$$) {
    $$$
  }
}'

# Let's also check for any port/group validation in the code
rg "port.*=.*kwargs\.get.*" -A 2
rg "group.*=.*kwargs\.get.*" -A 2

```

Length of output: 936

---

_Originally posted by @coderabbitai[bot] in https://github.com/reactive-firewall/multicast/pull/184#pullrequestreview-2446690171_

**Comment by reactive-firewall** [comment]
also consider:
```bash
#! /bin/bash
# Description: Verify the method implementation and its usage across the codebase

# Check for the new method implementation
ast-grep --pattern $'def _should_get_package_version_WHEN_valid(self):
  $$$'

# Check for any remaining old method calls
rg '_get_package_version\(' --type py
```

**Comment by reactive-firewall** [comment]
also consider:
```bash
#! /bin/bash

# Check for other test files that might conflict or complement this test suite
printf "Checking for related test files...\n"
fd -t f -e py "test_.*server.*\.py$" tests/

# Look for McastServer usage across the codebase
printf "\nChecking McastServer usage...\n"
rg -l "class McastServer"

# Check for potential test gaps by looking for untested methods
printf "\nChecking for potentially untested server methods...\n"
ast-grep --pattern 'class McastServer {
  $$$
  def $METHOD($$$) {
    $$$
  }
  $$$
}'
```

**Comment by reactive-firewall** [comment]
also consider:
```bash
#!/bin/bash
# Search for property definitions and message/exit_code handling in CommandExecutionError
ast-grep --pattern 'class CommandExecutionError {
  $$$
  message = $$$
  $$$
}'

# Get the complete implementation of the class
rg -A 20 'class CommandExecutionError' multicast/exceptions.py

```
---
also consider:
```bash
#!/bin/bash
# Search for the complete implementation of CommandExecutionError class
ast-grep --pattern 'class CommandExecutionError {
  $$$
  __init__($$$) {
    $$$
  }
  $$$
}'

# Search for any properties or methods defined in CommandExecutionError
rg -A 2 'def ' multicast/exceptions.py
```
---
also consider:
```bash
#!/bin/bash
# Description: Check for any untested methods or properties in CommandExecutionError

# Search for CommandExecutionError implementation
ast-grep --pattern 'class CommandExecutionError {
  $$$
}'

# Search for any properties or methods that might need testing
rg -A 5 'CommandExecutionError' --type py
```

**Comment by reactive-firewall** [comment]
@coderabbitai, consider the discussions in this GHI ( #207 ) and walk me through implementing the specific `ast-grep` patterns as re-useable configurations/rules/templates (e.g. however `ast-grep` usually configures these kinds of things), including the specific suggested implementations. Consider the primary goal of this larger task is to configure `ast-grep` used in your reviews to include these kinds of checks.

**Comment by reactive-firewall** [comment]
@coderabbitai please continue and Add rules for documentation standards, namely based on [CEP-7](https://gist.github.com/reactive-firewall/123b8a45f1bdeb064079e0524a29ec20)

**Comment by reactive-firewall** [comment]
@coderabbitai

# Plan

Here are the initial rules I'll implement and try out initially:

## [CEP-7](https://gist.github.com/reactive-firewall/123b8a45f1bdeb064079e0524a29ec20) Rules

File: `.ast-grep/multicast-qa-rules.yml`

```yaml
# .ast-grep/multicast-qa-rules.yml
rules:
  - id: require-docstring-testing
    pattern: |
      class $CLASS:
        $DOCSTRING
        $BODY
    message: "Class must include docstring with testing examples"
    where:
      includes:
        $DOCSTRING: /\"\"\".*Minimal Acceptance Testing:.*\"\"\"/s

  - id: enforce-testcase-format
    pattern: |
      """$DOC"""
    where:
      includes:
        $DOC: /Testcase \d+:.+?>>>.+?True/s
    message: "Test cases must follow format: Testcase N: description followed by assertions"

  - id: verify-magic-variables
    pattern: |
      __$NAME__ = $VALUE
    message: "Magic variables must be properly initialized with string values"
    where:
      includes:
        $NAME: ["module", "name", "file", "package", "doc"]

  - id: validate-method-docstring
    pattern: |
      def $METHOD($ARGS):
          """$DOC"""
    message: "Method must have docstring with testing examples"
    where:
      includes:
        $DOC: /.*Testing:.*>>>.+?>>>/s

```

## Safety Rules

File: `.ast-grep/multicast-safety-rules.yml`

```yaml
# .ast-grep/multicast-safety-rules.yml
rules:
  - id: check-error-chaining
    pattern: |
      try:
          $BODY
      except $EXCEPTION as $ERR:
          $HANDLER
    message: "Error handling must include proper exception handling and logging"
    where:
      includes:
        $HANDLER: /raise.*from/

  - id: validate-port-range
    pattern: |
      $PORT = $VALUE
    where:
      includes:
        $VALUE: /[^5]\d{4}/
    message: "Port values should be within the dynamic range (49152-65535) or documented range"

  - id: check-multicast-group
    pattern: |
      $GROUP = $VALUE
    where:
      includes:
        $VALUE: /"[^2].*\.\d+\.\d+\.\d+"/
    message: "Multicast group address must be in valid range (224.0.0.0 to 239.255.255.255)"

  - id: enforce-parameter-validation
    pattern: |
      def $METHOD(**$KWARGS):
          if $CONDITION in $KWARGS:
              $VALUE = $KWARGS.get($KEY, $DEFAULT)
    message: "Method must validate kwargs parameters with proper defaults"

  - id: verify-return-tuple
    pattern: |
      return ($SUCCESS, $RESULT)
    message: "Methods should return tuple of (success_bool, result)"
```

## Testing and [CEP-9](https://gist.github.com/reactive-firewall/d840ee9990e65f302ce2a8d78ebe73f6) Rules

File: `.ast-grep/multicast-test-rules.yml`

```yaml
# .ast-grep/multicast-test-rules.yml
rules:
  - id: require-test-fixtures
    pattern: |
      class $TEST_CLASS(unittest.TestCase):
          $SETUP
    where:
      includes:
        $SETUP: /def setUp/
    message: "Test classes must include setUp method for fixtures"

  - id: verify-test-naming
    pattern: |
      def test_$NAME_WHEN_$CONDITION_GIVEN_$INPUT
    message: "[CEP-9](https://gist.github.com/reactive-firewall/d840ee9990e65f302ce2a8d78ebe73f6) Test methods must follow naming convention: test_<what>_WHEN_<condition>_GIVEN_<input>"

  - id: check-test-documentation
    pattern: |
      """$DOC"""
    where:
      includes:
        $DOC: /(Verif|Check|Test).*\n.*Args:.*\n.*Returns:/s
    message: "Test documentation must include purpose, args, and returns sections"
```

## Multicast Project Rules

File: `.ast-grep/mcast_rules.yml`

```yaml
# .ast-grep/mcast_rules.yml
rules:
  # Rule for multicast server implementation patterns
  mcast-server-pattern:
    pattern: |
      class Mcast$TYPE:
        $$$
        def doStep(self, $ARGS):
          $$$
    language: python
    message: "Verify Mcast server implementation follows standard pattern"
    severity: error

  # Rule for exception handling pattern
  exception-pattern:
    pattern: |
      try:
        $$$
      except Exception as err:
        raise CommandExecutionError(str(err))
    language: python
    message: "Ensure proper exception handling with CommandExecutionError"
    severity: warning

  # Rule for test class patterns
  test-class-pattern:
    pattern: |
      class Test$NAME($$$):
        $$$
        def test_$METHOD_WHEN_$CONDITION(self):
          $$$
    language: python
    message: "Test classes should follow naming convention and include WHEN conditions"
    severity: warning

  # Rule for UDP client implementation
  udp-client-pattern:
    pattern: |
      class MulticastUDPClient($$$):
        $$$
        def __init__(self, $$$):
          $$$
        def $METHOD(self, $$$):
          $$$
    language: python
    message: "Verify UDP client implementation follows project standards"
    severity: error

  # Rule for module initialization
  module-init-pattern:
    pattern: |
      """$$$"""
      
      from $$$
      
      __version__ = $VERSION
    language: python
    message: "Module initialization should include docstring and version"
    severity: warning
```
