### ISSUE TITLE
v2.0.x Chore - Improve CI by refactoring workaround upgrade action

### ISSUE THREAD

**Issue by reactive-firewall** [reactive-firewall/multicast#210]
Refactor windows upgrade action.
<details>
<summary>.github/workflows/Tests.yml (3)</summary><blockquote>

`2-7`: **Consider using more specific branch patterns for HOTFIX.**

The wildcard pattern `HOTFIX-*` might be too broad. Consider using a more specific pattern like `HOTFIX-[0-9]*` to ensure only properly formatted hotfix branches trigger the workflow.

```diff
-      - HOTFIX-*
+      - HOTFIX-[0-9]*
```

---

`224-226`: **Windows-specific pip upgrade step needs refinement.**

The Windows-specific pip upgrade steps are duplicated. Consider extracting this into a reusable composite action to follow DRY principle.

Create a new file `.github/actions/upgrade-windows-pip/action.yml`:
```yaml
name: 'Upgrade Windows Pip'
description: 'Fixes Windows pip issues by upgrading'
runs:
  using: "composite"
  steps:
    - run: python -m pip install --upgrade pip
      shell: bash
      if: ${{ runner.os == 'Windows' }}
```

Then replace the duplicate steps with:
```diff
-    - name: Fix braindead windows ${{ matrix.python-version }} on ${{ matrix.os }}
-      if: ${{ !cancelled() && runner.os == 'Windows' }}
-      run: python -m pip install --upgrade pip
+    - uses: ./.github/actions/upgrade-windows-pip
```

Also applies to: 609-611
</blockquote></details>

_Originally posted by @coderabbitai[bot] in https://github.com/reactive-firewall/multicast/pull/184#pullrequestreview-2441690518_
